object Versions {
    const val coreKtx  ="1.12.0"
    const val appcompat  ="1.6.1"
    const val lifecycleRuntimeKtx  ="2.6.2"
    const val activityCompose  ="1.8.2"
    const val compose  ="2023.08.00"
    const val material  ="1.9.0"
    const val junit  ="1.1.5"
    const val JUnit4  ="4.13.2"
    const val espressoCore  ="3.5.1"
    const val navigationCompose  ="1.1.5"
    const val lifecycleViewModelKtx  ="2.6.1"
    const val hiltAndroid  ="2.48"
    const val hiltCompiler  ="1.1.0-alpha01"
}